### ISSUE TITLE
Missed arm_neon.h, urging your help(about compile on X86 instructions)

### ISSUE THREAD

**Issue by Justjustifyjudge** [jfikar/xhpl-aarch64#2]
![image](https://github.com/user-attachments/assets/9764ded8-94c8-486c-8eeb-433894a34ffa)
when I try to compile the process by "NO_FORTRAN=1 NUM_THREADS=8 USE_OPENMP=1 make -j$(nproc)", it seems that happened to can't find the arm_neon.h.
Any help from you will be greatly appreciated. TvT

**Comment by jfikar** [comment]
Hi,
I think, you are trying to compile ARM version on X86, right? Is it a cross-compile? Here, I've described only native compile on ARM64. Native compile should work almost the same on X86, what do you set as TARGET?

**Comment by Justjustifyjudge** [comment]
Yes! I think you're right! Thank you very very much! I tried to compile on X86, the TARGET parameter I tried includes default(empty), ARMV8, CORTEXA53 and CORTEXA55. It seems that all version came into this problem--
![image](https://github.com/user-attachments/assets/ebfe5cad-39fa-41f0-b3de-66b9ba209f9b)

**Comment by jfikar** [comment]
It should work on x86. The missing arm_neon.h comes as you request an ARM CPU: ARMV8, CORTEXA53, and CORTEXA55.

Without anything it should autodetect your CPU. But if you already executed e.g. `export TATGET=ARMV8`, it will stay set until you do `unset TARGET`.

You may also specify the x86 TARGET directly, the allowed keywords are [in the Target.List.txt file](https://github.com/OpenMathLib/OpenBLAS/blob/develop/TargetList.txt)

**Comment by Justjustifyjudge** [comment]
Thank you! Now I can run up the process. You are right--it is me haven't unset the TARGET parameter, that is why I came into to this fault. When I unset first then let it autodetect my cpu, the process successfully run on. I'm really appreciate your help, again, thank you!❤️
